# Generated by Django 5.1.6 on 2025-02-09 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitlists', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WaitListEnty',
            new_name='WaitListEntry',
        ),
    ]
